name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-unix:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-10.15, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: test-gcc
      run: g++ -std=c++11 -g -Wall -Wextra main.cpp -o main && ./main
    - name: test-clang
      run: clang++ -std=c++11 -g -Wall -Wextra main.cpp -o main && ./main
      
  build-win:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: test-msvc
      run: cl main.cpp && ./main.exe
